### PR TITLE
Don't assume local repo with cedar-policy

### PR DESCRIPTION
**Pull request by andrewmwells-amazon**
Don't assume local repo with cedar-policy

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by aaronjeline — APPROVED** [review]

**Comment by khieta** [comment]
@andrewmwells-amazon I think we want to leave this as-is. I updated it in #43 since the `main` branch requires the latest version of `cedar-policy` -- not the version on crates.io. We definitely want the crates.io version in the `release/x.x.x` branches though.

**Review by andrewmwells-amazon — COMMENTED** [review]
Changed to a comment explaining why we need `path`

**Comment by andrewmwells-amazon** [comment]
> @andrewmwells-amazon I think we want to leave this as-is. I updated it in https://github.com/cedar-policy/cedar-java/pull/43 since the main branch requires the latest version of cedar-policy -- not the version on crates.io. We definitely want the crates.io version in the release/x.x.x branches though.

I see. Not ideal, but probably ok for now. It breaks cedar-java-hello-world, but I think it's reasonable for that to depend on a release instead of `main`. Added a comment and we can fix it after the next `cedar-policy` release.

**Review by khieta — APPROVED** [review]

**Comment by khieta** [comment]
> I see. Not ideal, but probably ok for now. It breaks cedar-java-hello-world, but I think it's reasonable for that to depend on a release instead of main. Added a comment and we can fix it after the next cedar-policy release.

We may run into this situation again in the future (un-released breaking changes on the `main` branch in `cedar`) so there may not be a great fix. I think we just want to redirect all users to the release branches (and the released version on Maven, once available).

But this is a bit of a foot gun currently: should we switch to using `release/2.3.x` as the default branch, and rename `main` to `experimental`?

**Pull request merged**
