### PR TITLE
Cherry-pick #202

### PR DESCRIPTION
**Pull request by amzn-mdamine**
Cherry-pick #202

### CODE REVIEW

**Review by khieta — APPROVED** [review]

**Comment by shaobo-he-aws** [comment]
I'm looking into it. There seems to be some issues with the release branch.

**Comment by amzn-mdamine** [comment]
I have verified the build and tests locally, and everything is passing on my machine. However, it seems that the CI pipeline is still failing. I'll investigate further to identify the root cause of the issue and provide an update.

**Comment by khieta** [comment]
The failure may be resolved by #209 -- try merging with the latest `release/4.0.x` branch

**Comment by shaobo-he-aws** [comment]
#210 should fix it.

**Comment by shaobo-he-aws** [comment]
@amzn-mdamine could you please rebase or merge with `release/4.0.x`?

**Comment by amzn-mdamine** [comment]
I did the rebase.

**Review by khieta — APPROVED** [review]

**Review by shaobo-he-aws — APPROVED** [review]

**Pull request merged**
